packages:
  - userscripts/*
  - lib/*
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - vite@8.0.16
  - '@babel/core@7.29.1'
overrides:
  '@babel/core@<=7.29.0': ^7.29.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  vite@>=8.0.0 <=8.0.15: ^8.0.16
