import { writeFile } from 'node:fs/promises';

const letters = Array.from({ length: 26 }, (_, i) =>
  String.fromCharCode(0x61 + i)
);

async function main() {
  const pre = `// AUTOMATICALLY GENERATED BY \`flow.gen.ts\`\n\nexport const flow: {\n\n`;
  const post = `\n\n} = (value: any, ...fns: Function[]) => fns.reduce((x, f) => f(x), value);\n`;
  const lines: string[] = [];
  const MAX = 10;
  if (!(MAX <= 26)) throw new Error();
  for (let i = 0; i < MAX; i++) {
    lines.push(
      `${i === MAX ? '' : '   '.repeat(MAX - i - 1)}<${letters.slice(0, i + 1).join(', ')}>(value: a${letters
        .slice(0, i)
        .map((x, i) => `, fn${i}: (_: ${x}) => ${letters[i + 1]}`)
        .join('')}): ${letters[i]};`
    );
  }
  await writeFile('./function/flow.ts', `${pre}${lines.join('\n')}${post}`);
}

main();
